const Partylevel = [
    { level: 1, name: "Spectator", drunkennessText: 0.2 },
    { level: 2, name: "Socialite", drunkennessText: 0.4 },
    { level: 3, name: "Dance Enthusiast", drunkennessText: 0.6 },
    { level: 4, name: "Bar Regular", drunkennessText: 0.8 },
    { level: 5, name: "Night Owl", drunkennessText: 1.0 },
    { level: 6, name: "Party Starter", drunkennessText: 1.2 },
    { level: 7, name: "Drunken Dancer", drunkennessText: 1.4 },
    { level: 8, name: "Liquor Lover", drunkennessText: 1.6 },
    { level: 9, name: "Cocktail Connoisseur", drunkennessText: 1.8 },
    { level: 10, name: "Dance Floor Dominator", drunkennessText: 2.0 },
    { level: 11, name: "Bar Kingpin", drunkennessText: 2.2 },
    { level: 12, name: "Midnight Reveler", drunkennessText: 2.4 },
    { level: 13, name: "Mixer Master", drunkennessText: 2.6 },
    { level: 14, name: "Rave Ruler", drunkennessText: 2.8 },
    { level: 15, name: "Intoxication Innovator", drunkennessText: 3.0 },
    { level: 16, name: "Spirits Specialist", drunkennessText: 3.2 },
    { level: 17, name: "Nightlife Navigator", drunkennessText: 3.4 },
    { level: 18, name: "Booze Buff", drunkennessText: 3.6 },
    { level: 19, name: "Grand Gamboler", drunkennessText: 3.8 },
    { level: 20, name: "Party Maestro", drunkennessText: 4.0 },
    { level: 21, name: "Strategic Sipper", drunkennessText: 4.2 },
    { level: 22, name: "Barracks Boozehound", drunkennessText: 4.4 },
    { level: 23, name: "Commander of Cocktails", drunkennessText: 4.6 },
    { level: 24, name: "Rum Regiment Leader", drunkennessText: 4.8 },
    { level: 25, name: "Gin General", drunkennessText: 5.0 },
    { level: 26, name: "Vodka Vanguard", drunkennessText: 5.2 },
    { level: 27, name: "Tequila Tactician", drunkennessText: 5.4 },
    { level: 28, name: "Whiskey Warlord", drunkennessText: 5.6 },
    { level: 29, name: "Battlefield Boozer", drunkennessText: 5.8 },
    { level: 30, name: "Infantry Inebriator", drunkennessText: 6.0 },
    { level: 31, name: "Tankard Tactician", drunkennessText: 6.2 },
    { level: 32, name: "Artillery Alcoholic", drunkennessText: 6.4 },
    { level: 33, name: "Drunken Drill Sergeant", drunkennessText: 6.6 },
    { level: 34, name: "Intoxicated Colonel", drunkennessText: 6.8 },
    { level: 35, name: "Naval Nightcrawler", drunkennessText: 7.0 },
    { level: 36, name: "Airborne Ale Aviator", drunkennessText: 7.2 },
    { level: 37, name: "Special Ops Sipper", drunkennessText: 7.4 },
    { level: 38, name: "Combat Cocktails Commander", drunkennessText: 7.6 },
    { level: 39, name: "Warzone Whiskey Wielder", drunkennessText: 7.8 },
    { level: 40, name: "Division Drunkard", drunkennessText: 8.0 },
    { level: 41, name: "Corps Commando", drunkennessText: 8.2 },
    { level: 42, name: "Battalion Bourbon Baron", drunkennessText: 8.4 },
    { level: 43, name: "Squadron Scotch Sipper", drunkennessText: 8.6 },
    { level: 44, name: "Brigade Beer Brigadier", drunkennessText: 8.8 },
    { level: 45, name: "Platoon Party Planner", drunkennessText: 9.0 },
    { level: 46, name: "Regimental Rum Reveler", drunkennessText: 9.2 },
    { level: 47, name: "Special Forces Spirits Specialist", drunkennessText: 9.4 },
    { level: 48, name: "Navy Nightlife Navigator", drunkennessText: 9.6 },
    { level: 49, name: "Marine Mixer Master", drunkennessText: 9.8 },
    { level: 50, name: "Admiral of Afterhours", drunkennessText: 10.0 },
    { level: 51, name: "Sergeant of Shots", drunkennessText: 10.2 },
{ level: 52, name: "Rum Runner", drunkennessText: 10.4 },
{ level: 53, name: "Gin Gladiator", drunkennessText: 10.6 },
{ level: 54, name: "Vodka Virtuoso", drunkennessText: 10.8 },
{ level: 55, name: "Tequila Temptation", drunkennessText: 11.0 },
{ level: 56, name: "Whiskey Wizard", drunkennessText: 11.2 },
{ level: 57, name: "Beer Baron", drunkennessText: 11.4 },
{ level: 58, name: "Cocktail Crusader", drunkennessText: 11.6 },
{ level: 59, name: "Majestic Mixer", drunkennessText: 11.8 },
{ level: 60, name: "Drunken Diplomat", drunkennessText: 12.0 },
{ level: 61, name: "Bourbon Benefactor", drunkennessText: 12.2 },
{ level: 62, name: "Scotch Scholar", drunkennessText: 12.4 },
{ level: 63, name: "Beer Connoisseur", drunkennessText: 12.6 },
{ level: 64, name: "Margarita Maestro", drunkennessText: 12.8 },
{ level: 65, name: "Martini Mastermind", drunkennessText: 13.0 },
{ level: 66, name: "Whiskey Whiz", drunkennessText: 13.2 },
{ level: 67, name: "Rum Reveler", drunkennessText: 13.4 },
{ level: 68, name: "Gin Guru", drunkennessText: 13.6 },
{ level: 69, name: "Vodka Veteran", drunkennessText: 13.8 },
{ level: 70, name: "Tequila Trailblazer", drunkennessText: 14.0 },
{ level: 71, name: "Cocktail Commander", drunkennessText: 14.2 },
{ level: 72, name: "Spirits Strategist", drunkennessText: 14.4 },
{ level: 73, name: "Beer Battlemaster", drunkennessText: 14.6 },
{ level: 74, name: "Mixology Marvel", drunkennessText: 14.8 },
{ level: 75, name: "Intoxication Inventor", drunkennessText: 15.0 },
{ level: 76, name: "Sipper Supreme", drunkennessText: 15.2 },
{ level: 77, name: "Booze Brigadier", drunkennessText: 15.4 },
{ level: 78, name: "Grandmaster of Libations", drunkennessText: 15.6 },
{ level: 79, name: "Liquor Luminary", drunkennessText: 15.8 },
{ level: 80, name: "Party Pioneer", drunkennessText: 16.0 },
{ level: 81, name: "Saucy Strategist", drunkennessText: 16.2 },
{ level: 82, name: "Brew Baron", drunkennessText: 16.4 },
{ level: 83, name: "Cask Crusader", drunkennessText: 16.6 },
{ level: 84, name: "Tipple Tactician", drunkennessText: 16.8 },
{ level: 85, name: "Intrepid Inebriator", drunkennessText: 17.0 },
{ level: 86, name: "Cordial Conqueror", drunkennessText: 17.2 },
{ level: 87, name: "Whiskey Warden", drunkennessText: 17.4 },
{ level: 88, name: "Rum Ranger", drunkennessText: 17.6 },
{ level: 89, name: "Gin Guardian", drunkennessText: 17.8 },
{ level: 90, name: "Vodka Vigilante", drunkennessText: 18.0 },
{ level: 91, name: "Tequila Titan", drunkennessText: 18.2 },
{ level: 92, name: "Cocktail Captain", drunkennessText: 18.4 },
{ level: 93, name: "Spirits Sentinel", drunkennessText: 18.6 },
{ level: 94, name: "Beer Beneficiary", drunkennessText: 18.8 },
{ level: 95, name: "Libation Luminary", drunkennessText: 19.0 },
{ level: 96, name: "Party Proficient", drunkennessText: 19.2 },
{ level: 97, name: "Mirthful Mixer", drunkennessText: 19.4 },
{ level: 98, name: "Ale Artisan", drunkennessText: 19.6 },
{ level: 99, name: "Wine Wielder", drunkennessText: 19.8 },
{ level: 100, name: "Grand Pubmaster", drunkennessText: 20.0 }
];
export { Partylevel };
